#!/usr/bin/env python3
"""Regenerate slug-map.js and the inline REV_SLUG block in operator-template.html
from operators.json.

Rules:
- Existing unique slug -> id mappings are preserved.
- Where multiple ids share a slug (collision), the first id keeps the canonical
  slug; the rest get `<slug>-<id>`.
- Operators missing from any map get a generated slug: slugify(name)+'-'+zone,
  with `-<id>` appended if that collides with anything else.
- Output: slug-map.js (id -> slug) and REV_SLUG (slug -> id) in operator-template.html.
"""
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.abspath(__file__))


def slugify(text: str) -> str:
    s = text.lower()
    s = re.sub(r"[^\w\s-]", " ", s)
    s = re.sub(r"[\s_-]+", "-", s)
    return s.strip("-")


def parse_existing_slug_map(path: str) -> dict:
    """Extract id -> slug pairs from existing slug-map.js by regex."""
    if not os.path.exists(path):
        return {}
    text = open(path).read()
    pairs = re.findall(r'"([^"]+)"\s*:\s*"([^"]+)"', text)
    return {k: v for k, v in pairs}


def main() -> int:
    ops = json.load(open(os.path.join(BASE, "operators.json")))
    existing = parse_existing_slug_map(os.path.join(BASE, "slug-map.js"))

    # Build canonical id -> slug map.
    # Pass 1: pick canonical (first) id for each existing slug.
    slug_to_canonical_id: dict[str, str] = {}
    op_order = {o["id"]: i for i, o in enumerate(ops)}
    # Walk existing map in operator-order so the first record in operators.json
    # gets the canonical URL.
    sorted_existing = sorted(
        existing.items(), key=lambda kv: op_order.get(kv[0], 10**9)
    )
    for op_id, slug in sorted_existing:
        if slug not in slug_to_canonical_id:
            slug_to_canonical_id[slug] = op_id

    id_to_slug: dict[str, str] = {}
    used_slugs: set[str] = set()

    # Pass 2: assign canonical slug to the canonical id.
    for slug, op_id in slug_to_canonical_id.items():
        id_to_slug[op_id] = slug
        used_slugs.add(slug)

    op_by_id = {o["id"]: o for o in ops}

    # Pass 3: for collision losers (ids in `existing` not yet placed), append
    # `-<id>` to their canonical slug.
    for op_id, slug in existing.items():
        if op_id in id_to_slug:
            continue  # already canonical
        if op_id not in op_by_id:
            continue  # orphan in slug-map, drop
        candidate = f"{slug}-{op_id}"
        while candidate in used_slugs:
            candidate += "x"
        id_to_slug[op_id] = candidate
        used_slugs.add(candidate)

    # Pass 4: operators with no entry at all -> generate from name+zone.
    for op in ops:
        if op["id"] in id_to_slug:
            continue
        base = slugify(op.get("name", "") + " " + op.get("zone", ""))
        if not base:
            base = op["id"]
        candidate = base
        if candidate in used_slugs:
            candidate = f"{base}-{op['id']}"
        i = 2
        while candidate in used_slugs:
            candidate = f"{base}-{op['id']}-{i}"
            i += 1
        id_to_slug[op["id"]] = candidate
        used_slugs.add(candidate)

    # Sanity check: every operator covered, no slug collisions.
    assert len(id_to_slug) == len(ops), (
        f"id_to_slug={len(id_to_slug)} vs ops={len(ops)}"
    )
    assert len(set(id_to_slug.values())) == len(id_to_slug), (
        "duplicate slugs after regen"
    )

    # Write slug-map.js (id -> slug). Preserve original insertion order from
    # operators.json so diffs are minimal.
    entries = [(op["id"], id_to_slug[op["id"]]) for op in ops]
    body = ",".join(f'"{k}":"{v}"' for k, v in entries)
    slug_map_js = (
        "// Auto-generated by regen_slug_maps.py — do not hand-edit.\n"
        f"window._OP_SLUG_MAP = {{{body}}};\n"
    )
    with open(os.path.join(BASE, "slug-map.js"), "w") as f:
        f.write(slug_map_js)

    # Write REV_SLUG (slug -> id) into operator-template.html.
    rev_entries = ",".join(f'"{id_to_slug[o["id"]]}":"{o["id"]}"' for o in ops)
    template_path = os.path.join(BASE, "operator-template.html")
    template = open(template_path).read()
    new_rev = f"const REV_SLUG = {{{rev_entries}}};"
    template = re.sub(
        r"const REV_SLUG\s*=\s*\{[^;]+\};",
        new_rev,
        template,
        count=1,
        flags=re.DOTALL,
    )

    # Update operator count strings (footer + 404).
    count = len(ops)
    template = re.sub(
        r"(\d+\s+operators across Florida)",
        f"{count} operators across Florida",
        template,
    )
    template = re.sub(
        r"View all \d+ operators",
        f"View all {count} operators",
        template,
    )

    with open(template_path, "w") as f:
        f.write(template)

    print(f"Wrote {len(ops)} entries to slug-map.js")
    print(f"Wrote {len(ops)} entries to REV_SLUG in operator-template.html")
    print(f"Updated operator count to {count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
